# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
revisionHistoryLimit: 1
image:
  repository: jp.icr.io/app-sales/certificate-manager
  tag: '1.0'
  pullSecret: all-icr-io
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
  readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  # readinessProbe:
  #   httpGet:
  #     path: /ready
  #     port: 3000
  #   initialDelaySeconds: 3
  #   periodSeconds: 5
  livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  # livenessProbe:
  #   httpGet:
  #     path: /live
  #     port: 3000
  #   initialDelaySeconds: 40
  #   periodSeconds: 10
service:
  name: Cluster
  type: ClusterIP #ClusterIP or NodePort
  servicePort: 4000
  nodePort: 30400 #30000~32767の間
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag: v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
