# Install the app dependencies in a full Node docker images
FROM node:12

WORKDIR /app

# Install OS updates
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the dependencies into a Slim Node docker image
FROM node:12-slim

WORKDIR /app

# Install OS updates
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

# Install app dependencies
COPY --from=0 /app/node_modules /app/node_modules
COPY . /app

ENV NODE_ENV development
ENV PORT 4000

USER node

EXPOSE 4000
CMD ["npm", "start"]
