# Install the app dependencies in a full Node docker image
FROM node:12

# RUN mkdir -p /app
WORKDIR /app

# Install OS updates
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get clean
RUN echo 'Finished installing dependencies'

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the dependencies into a Slim Node docker image
FROM node:12-slim
WORKDIR /app

# Install OS updates
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get clean
RUN echo 'Finished installing dependencies'

RUN apt-get install git -y

# Install app dependencies
COPY --from=0 /app/node_modules /app/node_modules
COPY . /app

# submodule deploy
RUN git clone https://ToshiyukiWakasugi:05af7404bb590b8f0c1bcb83e3323c695741f4a6@github.com/traceOrg/trace-common-modules.git --branch product
RUN mv ./trace-common-modules/* ./src/submodules/

ENV NODE_ENV product-cloud
ENV PORT 4000
USER node
EXPOSE 4000
CMD ["npm","start"]
